[ui]
hideTopBar = true


[theme]
base = "dark"

# Primary accent color for interactive elements.
primaryColor = "#3498db"  # A shade of blue

# Background color for the main content area.
backgroundColor = "#2c3e50"  # A dark blue-gray

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#34495e"  # A slightly lighter blue-gray

# Color used for almost all text.
textColor = "#ecf0f1"  # Light grayish-white